# Generated by Django 3.0.2 on 2020-02-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Short Name')),
                ('start', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Proficiencies',
            },
        ),
        migrations.CreateModel(
            name='Schtick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tier')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SchtickType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Value')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_attribute', to='action.Attribute')),
                ('calculated_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_calculated_attribute', to='action.Attribute')),
                ('proficiency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_proficiency', to='action.Proficiency')),
                ('schtick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_schtick', to='action.Schtick')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_skill', to='action.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('valuepair_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.ValuePair')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
            bases=('action.valuepair',),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('valuepair_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.ValuePair')),
            ],
            bases=('action.valuepair',),
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('valuepair_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.ValuePair')),
            ],
            bases=('action.valuepair',),
        ),
        migrations.AddField(
            model_name='schtick',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.SchtickType'),
        ),
        migrations.CreateModel(
            name='SchtickMod',
            fields=[
                ('valuepair_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.ValuePair')),
                ('linked_schtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Schtick')),
            ],
            bases=('action.valuepair',),
        ),
        migrations.AddField(
            model_name='schtick',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schtickreq', to='action.Prereq'),
        ),
        migrations.CreateModel(
            name='Advancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Description')),
                ('schtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Schtick')),
                ('req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Prereq')),
            ],
        ),
    ]
