# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Short Name'),
        ),
    ]
