# Generated by Django 3.0.3 on 2020-02-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_proficiency_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='sortorder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='sortorder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='sortorder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
