# Generated by Django 3.0.3 on 2020-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20200203_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaw',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='schtickmod',
            name='divisor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schtickmod',
            name='multiplier',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
