# Generated by Django 3.0.3 on 2020-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_auto_20200321_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaw',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Description'),
        ),
    ]
