# Generated by Django 3.0.3 on 2020-03-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20200321_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'Character classes'},
        ),
        migrations.AlterModelOptions(
            name='classentry',
            options={'verbose_name_plural': 'Class entries'},
        ),
    ]
