# Generated by Django 3.0.3 on 2020-03-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_auto_20200321_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='classentry',
            name='flaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Flaw'),
        ),
        migrations.AlterField(
            model_name='classentry',
            name='schtick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Schtick'),
        ),
    ]
