# Generated by Django 3.0.3 on 2020-03-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_auto_20200321_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='schtickmod',
            name='linked_flaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Flaw'),
        ),
        migrations.AlterField(
            model_name='schtickmod',
            name='linked_schtick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='action.Schtick'),
        ),
    ]
