# Generated by Django 3.0.3 on 2020-03-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_auto_20200326_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('classes', models.BooleanField()),
                ('notes', models.CharField(max_length=120, verbose_name='Name')),
                ('starting_xp', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='schtick_list',
            field=models.ManyToManyField(related_name='characterclasses', to='action.SchtickType'),
        ),
        migrations.RemoveField(
            model_name='schtick',
            name='type',
        ),
        migrations.AddField(
            model_name='schtick',
            name='type',
            field=models.ManyToManyField(related_name='schticks', to='action.SchtickType'),
        ),
        migrations.CreateModel(
            name='XPprogression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveSmallIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='NotInCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Attribute')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Campaign')),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Flaw')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Proficiency')),
                ('schtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Schtick')),
                ('schtick_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.SchtickType')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Skill')),
            ],
        ),
    ]
