# Generated by Django 3.0.3 on 2020-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_auto_20200328_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpprogression',
            options={'verbose_name': 'XP Progression', 'verbose_name_plural': 'XP Progressions'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
    ]
