# Generated by Django 3.0.3 on 2020-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_auto_20200328_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancement',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='advancement',
            name='progression',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Progression'),
        ),
        migrations.AlterField(
            model_name='schtick',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cost'),
        ),
    ]
