# Generated by Django 3.0.3 on 2020-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0012_auto_20200329_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancement',
            old_name='points',
            new_name='cost',
        ),
    ]
