# Generated by Django 3.2.2 on 2021-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_auto_20200331_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schtick',
            name='req',
        ),
        migrations.AddField(
            model_name='schtick',
            name='req',
            field=models.ManyToManyField(related_name='schtickreq', to='action.Prereq'),
        ),
    ]
