# Generated by Django 3.2.2 on 2021-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0014_auto_20210507_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancement',
            options={'ordering': ('schtick', 'req', 'cost')},
        ),
        migrations.AlterModelOptions(
            name='flaw',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='prereq',
            options={'ordering': ('attribute', 'skill', 'proficiency', 'schtick', 'value')},
        ),
        migrations.AlterModelOptions(
            name='schticktype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='schtick',
            name='req',
            field=models.ManyToManyField(blank=True, null=True, related_name='schtickreq', to='action.Prereq'),
        ),
        migrations.AlterField(
            model_name='valuepair',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
