# Generated by Django 3.2.2 on 2021-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0015_auto_20210512_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='classentry',
            name='default',
            field=models.BooleanField(null=True, verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='classentry',
            name='divisor',
            field=models.BooleanField(null=True, verbose_name='Divisor'),
        ),
        migrations.AddField(
            model_name='classentry',
            name='optional',
            field=models.BooleanField(null=True, verbose_name='Optional'),
        ),
        migrations.AlterField(
            model_name='schtick',
            name='req',
            field=models.ManyToManyField(blank=True, related_name='schtickreq', to='action.Prereq'),
        ),
    ]
