# Generated by Django 3.2.2 on 2021-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_auto_20210518_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classentry',
            name='divisor',
            field=models.IntegerField(null=True, verbose_name='Divisor'),
        ),
    ]
