# Generated by Django 3.2.2 on 2021-05-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0019_alter_schticktype_schticktype_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaw',
            options={'ordering': ('name', 'value')},
        ),
        migrations.AlterModelOptions(
            name='prereq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valuepair',
            options={'ordering': ('value', 'schtick__name', 'proficiency__name', 'skill__name', 'attribute__name')},
        ),
        migrations.AlterField(
            model_name='schtick',
            name='req',
            field=models.ManyToManyField(blank=True, related_name='schtickreq', to='action.Prereq', verbose_name='prereqs'),
        ),
    ]
