# Generated by Django 3.0.2 on 2020-02-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Points')),
                ('notes', models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSchtick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('schtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Schtick')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Proficiency')),
            ],
            options={
                'verbose_name_plural': 'Proficiencies',
            },
        ),
        migrations.CreateModel(
            name='CharacterFlaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Flaw')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Attribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
            ],
        ),
    ]
