# Generated by Django 3.0.2 on 2020-01-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('charactermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.CharacterMixin')),
                ('points', models.SmallIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Skill')),
            ],
            bases=('character.charactermixin', models.Model),
        ),
        migrations.CreateModel(
            name='CharacterSchtick',
            fields=[
                ('charactermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.CharacterMixin')),
                ('points', models.SmallIntegerField()),
                ('schtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Schtick')),
            ],
            bases=('character.charactermixin', models.Model),
        ),
        migrations.CreateModel(
            name='CharacterProficiency',
            fields=[
                ('charactermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.CharacterMixin')),
                ('acquired', models.SmallIntegerField()),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Proficiency')),
            ],
            bases=('character.charactermixin', models.Model),
        ),
        migrations.CreateModel(
            name='CharacterFlaw',
            fields=[
                ('charactermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.CharacterMixin')),
                ('points', models.SmallIntegerField()),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Flaw')),
            ],
            bases=('character.charactermixin', models.Model),
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('charactermixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.CharacterMixin')),
                ('points', models.SmallIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Attribute')),
            ],
            bases=('character.charactermixin', models.Model),
        ),
    ]
