# Generated by Django 3.0.2 on 2020-02-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterproficiency',
            name='acquired',
            field=models.BooleanField(),
        ),
    ]
