# Generated by Django 3.0.2 on 2020-02-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200202_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattribute',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='characterflaw',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='characterproficiency',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='characterschtick',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes'),
        ),
    ]
