# Generated by Django 3.0.3 on 2020-02-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20200202_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterproficiency',
            name='character',
        ),
        migrations.AddField(
            model_name='characterproficiency',
            name='characterskill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='character.CharacterSkill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
