# Generated by Django 3.0.3 on 2020-03-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_auto_20200321_0108'),
        ('character', '0004_auto_20200218_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterproficiency',
            options={'verbose_name_plural': 'Character Proficiencies'},
        ),
        migrations.CreateModel(
            name='CharacterClassEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('classentry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.ClassEntry')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=120, verbose_name='Level')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
                ('characterclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.CharacterClass')),
            ],
        ),
    ]
