# Generated by Django 3.0.3 on 2020-03-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20200326_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclassentry',
            name='notes',
            field=models.CharField(default='', max_length=120, verbose_name='Notes'),
            preserve_default=False,
        ),
    ]
