# Generated by Django 3.0.3 on 2020-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_auto_20200326_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercharacterclass',
            name='level',
            field=models.CharField(choices=[('Heroic', 'Heroic'), ('Epic', 'Epic'), ('Basic', 'Basic')], max_length=120, verbose_name='Level'),
        ),
    ]
