# Generated by Django 3.0.3 on 2020-03-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_auto_20200331_1848'),
        ('character', '0009_auto_20200326_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterschtick',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='CharacterAdvancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=120, null=True, verbose_name='Notes')),
                ('advancement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='action.Advancement')),
                ('characterschtick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.CharacterSchtick')),
            ],
        ),
    ]
