# Generated by Django 3.0.3 on 2020-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20200331_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteradvancement',
            name='points',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
