# Generated by Django 3.0.3 on 2020-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20200331_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclassentry',
            name='points',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
