# Generated by Django 3.0.3 on 2020-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_auto_20200409_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclassentry',
            name='points',
        ),
    ]
