# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_auto_20200409_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercharacterclass',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Epic', 'Epic'), ('Heroic', 'Heroic')], max_length=120, verbose_name='Level'),
        ),
    ]
