# Generated by Django 3.2.2 on 2021-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0018_auto_20210518_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercharacterclass',
            name='level',
            field=models.CharField(choices=[('Epic', 'Epic'), ('Heroic', 'Heroic'), ('Basic', 'Basic')], max_length=120, verbose_name='Level'),
        ),
    ]
