# Generated by Django 3.2.2 on 2021-05-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0019_alter_charactercharacterclass_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercharacterclass',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Epic', 'Epic'), ('Heroic', 'Heroic')], max_length=120, verbose_name='Level'),
        ),
    ]
